# Generated by Django 4.2.6 on 2023-10-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holken',
            fields=[
                ('num_holken', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_holken', models.CharField(max_length=50)),
                ('puntos', models.IntegerField()),
            ],
        ),
    ]
