# Generated by Django 4.2.6 on 2023-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holken',
            name='equipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holken',
            name='rol',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
