# Generated by Django 4.2.6 on 2023-10-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_holken_equipo_holken_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='holken',
            name='avatar',
            field=models.ImageField(null=True, upload_to='holken'),
        ),
    ]
