# Generated by Django 4.2.6 on 2023-10-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_holken_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holken',
            name='avatar',
            field=models.ImageField(null=True, upload_to='holken/'),
        ),
    ]
